<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/diuazrh0o/image/upload/v1554611308/d0876543-4ced-4a98-9854-fc78db89ecc7.jpg" alt="Gift Henshaw">
                        <h6>Gift Henshaw</h6>
                        <p>Front end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/inyamugift" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/giftshaw" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am new to coding, I hope to give my best to learn to become a developer, I do not mind being pressured to go extra mile to meet up</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML, little of CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
